# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  JavaScript: true
  Python: true
engines:
  eslint:
    enabled: true
exclude_paths:
- "lib/**/*"
- "bin/**/*"
- "examples/**/*"
